import type { Business, Review } from "./types";

export const businesses: Business[] = [
  {
    id: "harbor-cafe",
    name: "Harbor Cafe",
    category: "Cafe",
    location: "Riverside",
    shortDescription: "Cozy coffee, light bites, and a calm workspace.",
    addressLine: "12 Riverwalk Ave, Riverside",
    averageRating: 4.5,
    ratingCount: 128,
    averageBreakdown: { quality: 4.6, service: 4.4, value: 4.3 },
  },
  {
    id: "midtown-bites",
    name: "Midtown Bites",
    category: "Restaurant",
    location: "Midtown",
    shortDescription: "Modern comfort food with seasonal specials.",
    addressLine: "88 Market St, Midtown",
    averageRating: 4.2,
    ratingCount: 94,
    averageBreakdown: { quality: 4.2, service: 4.1, value: 4.0 },
  },
  {
    id: "paper-lantern-books",
    name: "Paper Lantern Books",
    category: "Bookstore",
    location: "Downtown",
    shortDescription: "Indie bookstore with staff picks and events.",
    addressLine: "210 Cedar Rd, Downtown",
    averageRating: 4.8,
    ratingCount: 61,
    averageBreakdown: { quality: 4.8, service: 4.7, value: 4.5 },
  },
  {
    id: "uptown-crumb",
    name: "Uptown Crumb Bakery",
    category: "Bakery",
    location: "Uptown",
    shortDescription: "Fresh bread, pastries, and espresso daily.",
    addressLine: "5 Alder Blvd, Uptown",
    averageRating: 4.4,
    ratingCount: 76,
    averageBreakdown: { quality: 4.5, service: 4.2, value: 4.1 },
  },
  {
    id: "iron-yard-gym",
    name: "Iron Yard Gym",
    category: "Gym",
    location: "Midtown",
    shortDescription: "Strength training, classes, and friendly coaches.",
    addressLine: "33 Atlas Way, Midtown",
    averageRating: 4.0,
    ratingCount: 142,
    averageBreakdown: { quality: 4.1, service: 3.9, value: 3.8 },
  },
  {
    id: "studio-satin",
    name: "Studio Satin Salon",
    category: "Salon",
    location: "Downtown",
    shortDescription: "Cuts, color, and styling with consultation-first care.",
    addressLine: "19 Blossom Ln, Downtown",
    averageRating: 4.3,
    ratingCount: 57,
    averageBreakdown: { quality: 4.4, service: 4.3, value: 4.0 },
  },
];

export const reviews: Review[] = [
  {
    id: "r1",
    businessId: "harbor-cafe",
    authorName: "Avery",
    createdAtISO: "2026-02-12T10:12:00.000Z",
    ratings: { quality: 5, service: 4, value: 4 },
    overall: 4.5,
    title: "Great spot to work",
    body: "Fast Wi‑Fi, plenty of outlets, and the latte was excellent. It gets busy around noon.",
  },
  {
    id: "r2",
    businessId: "harbor-cafe",
    authorName: "Jordan",
    createdAtISO: "2026-01-28T16:40:00.000Z",
    ratings: { quality: 4, service: 4, value: 4 },
    overall: 4.0,
    title: "Solid coffee and snacks",
    body: "Friendly staff and consistently good drip coffee. Pastries sell out quickly.",
  },
  {
    id: "r3",
    businessId: "paper-lantern-books",
    authorName: "Sam",
    createdAtISO: "2026-02-02T19:05:00.000Z",
    ratings: { quality: 5, service: 5, value: 4 },
    overall: 4.8,
    title: "Best indie bookstore",
    body: "Wonderful recommendations and a great selection. Prices are fair for an independent shop.",
  },
  {
    id: "r4",
    businessId: "midtown-bites",
    authorName: "Casey",
    createdAtISO: "2026-03-01T01:15:00.000Z",
    ratings: { quality: 4, service: 4, value: 4 },
    overall: 4.2,
    title: "Consistently good",
    body: "Tasty specials and quick service. The portions are reasonable and the menu rotates often.",
  },
  {
    id: "r5",
    businessId: "uptown-crumb",
    authorName: "Riley",
    createdAtISO: "2026-02-20T08:22:00.000Z",
    ratings: { quality: 5, service: 4, value: 4 },
    overall: 4.4,
    title: "Amazing pastries",
    body: "Croissants are flaky and fresh. Staff was helpful even during the morning rush.",
  },
  {
    id: "r6",
    businessId: "iron-yard-gym",
    authorName: "Taylor",
    createdAtISO: "2026-01-10T14:00:00.000Z",
    ratings: { quality: 4, service: 4, value: 3 },
    overall: 4.0,
    title: "Great equipment, a bit pricey",
    body: "Everything is clean and the equipment is well maintained. Membership cost is on the higher side.",
  },
  {
    id: "r7",
    businessId: "studio-satin",
    authorName: "Morgan",
    createdAtISO: "2026-02-26T17:33:00.000Z",
    ratings: { quality: 5, service: 5, value: 4 },
    overall: 4.7,
    title: "Loved my cut",
    body: "They listened carefully and nailed the style. Booking was easy and the studio is bright and clean.",
  },
];

export function getReviewsForBusiness(businessId: string): Review[] {
  return reviews
    .filter((r) => r.businessId === businessId)
    .slice()
    .sort((a, b) => b.createdAtISO.localeCompare(a.createdAtISO));
}

